[build]
  command = "npm install --include=dev && npm run build"
  publish = "dist/client"

[dev]
  command = "npm run dev"
  targetPort = 3000
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/server/**"]

[build.environment]
  NODE_VERSION = "20"
